# Generated by Django 3.0.3 on 2020-02-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0004_auto_20200228_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='readtext',
            field=models.CharField(blank=True, default='a', max_length=100, null=True),
        ),
    ]
